# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Pylint/mypy/black/isort
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        pytest --pylint --black --isort --mypy --cache-clear -v
    - name: Test with pytest
      run: |
        pytest --cov --cov-report html -v test
    - uses: actions/upload-artifact@v3
      with:
          name: coverage-artifact
          path: htmlcov/

    - uses: khaeru/coverage-gh@main
      with:
        # Token used to report checks. Required.
        token: ${{ github.token }}

        # Location of the coverage data file. Optional.
        #
        # Default: .coverage, in the GitHub Actions workspace directory.
        data-file: .coverage

        # Percent coverage required for the check to pass. Optional.
        #
        # This is a floating-point number between 0 and 100.
        #
        # Default: 100.0
        threshold: 100.0
